language: node_js
node_js:
  - "0.10"

notifications:
  flowdock: 0a08322200a820a400672ad55c8e37e9

before_script:
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958

services:
  - mongodb
